name: type_fast
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  build_runner: ^2.4.14
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.6+1
  flutter_native_splash: ^2.4.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  package_info_plus: ^8.2.1
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
